[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read-write", path = "./lib/blockchain/contracts" }]

[rpc_endpoints]
local = "${BLOCKCHAIN_RPC_URL}"

[fmt]
line_length = 100
