/**
 * Curated NSE-listed Indian equities for DEFINN academic simulation.
 * Reference prices are seed values — not live exchange quotes.
 * Company names, sectors, and ISINs are for educational identification only.
 */

export type UniverseStock = {
  symbol: string;
  companyName: string;
  exchange: "NSE" | "BSE";
  isin: string;
  sector: string;
  instrumentType: "EQUITY";
  /** Reference seed price in INR for simulation bootstrap */
  referencePrice: number;
  /** Simulation beta vs market factor (academic parameter, not live beta) */
  beta: number;
  /** Sector sensitivity */
  sectorBeta: number;
  /** Base daily volatility (log-return scale) */
  baseVolatility: number;
  description: string;
};

export const INDIAN_STOCK_UNIVERSE: UniverseStock[] = [
  {
    symbol: "RELIANCE",
    companyName: "Reliance Industries Ltd.",
    exchange: "NSE",
    isin: "INE002A01018",
    sector: "ENERGY",
    instrumentType: "EQUITY",
    referencePrice: 1415,
    beta: 1.0,
    sectorBeta: 1.0,
    baseVolatility: 0.012,
    description: "Conglomerate — energy, retail, telecom (simulation reference).",
  },
  {
    symbol: "TCS",
    companyName: "Tata Consultancy Services Ltd.",
    exchange: "NSE",
    isin: "INE467B01029",
    sector: "IT",
    instrumentType: "EQUITY",
    referencePrice: 3850,
    beta: 0.9,
    sectorBeta: 1.1,
    baseVolatility: 0.011,
    description: "IT services — simulation reference only.",
  },
  {
    symbol: "INFY",
    companyName: "Infosys Ltd.",
    exchange: "NSE",
    isin: "INE009A01021",
    sector: "IT",
    instrumentType: "EQUITY",
    referencePrice: 1620,
    beta: 0.85,
    sectorBeta: 1.1,
    baseVolatility: 0.011,
    description: "IT services — simulation reference only.",
  },
  {
    symbol: "HDFCBANK",
    companyName: "HDFC Bank Ltd.",
    exchange: "NSE",
    isin: "INE040A01034",
    sector: "BANKING",
    instrumentType: "EQUITY",
    referencePrice: 1720,
    beta: 0.95,
    sectorBeta: 1.15,
    baseVolatility: 0.013,
    description: "Private sector bank — simulation reference only.",
  },
  {
    symbol: "ICICIBANK",
    companyName: "ICICI Bank Ltd.",
    exchange: "NSE",
    isin: "INE090A01021",
    sector: "BANKING",
    instrumentType: "EQUITY",
    referencePrice: 1180,
    beta: 1.05,
    sectorBeta: 1.15,
    baseVolatility: 0.014,
    description: "Private sector bank — simulation reference only.",
  },
  {
    symbol: "SBIN",
    companyName: "State Bank of India",
    exchange: "NSE",
    isin: "INE062A01020",
    sector: "BANKING",
    instrumentType: "EQUITY",
    referencePrice: 820,
    beta: 1.1,
    sectorBeta: 1.15,
    baseVolatility: 0.015,
    description: "Public sector bank — simulation reference only.",
  },
  {
    symbol: "ITC",
    companyName: "ITC Ltd.",
    exchange: "NSE",
    isin: "INE154A01025",
    sector: "FMCG",
    instrumentType: "EQUITY",
    referencePrice: 465,
    beta: 0.7,
    sectorBeta: 0.85,
    baseVolatility: 0.009,
    description: "FMCG conglomerate — simulation reference only.",
  },
  {
    symbol: "BHARTIARTL",
    companyName: "Bharti Airtel Ltd.",
    exchange: "NSE",
    isin: "INE397D01024",
    sector: "TELECOM",
    instrumentType: "EQUITY",
    referencePrice: 1580,
    beta: 0.95,
    sectorBeta: 1.0,
    baseVolatility: 0.012,
    description: "Telecommunications — simulation reference only.",
  },
  {
    symbol: "LT",
    companyName: "Larsen & Toubro Ltd.",
    exchange: "NSE",
    isin: "INE018A01030",
    sector: "INDUSTRIALS",
    instrumentType: "EQUITY",
    referencePrice: 3580,
    beta: 1.05,
    sectorBeta: 1.05,
    baseVolatility: 0.012,
    description: "Engineering & construction — simulation reference only.",
  },
  {
    symbol: "AXISBANK",
    companyName: "Axis Bank Ltd.",
    exchange: "NSE",
    isin: "INE238A01034",
    sector: "BANKING",
    instrumentType: "EQUITY",
    referencePrice: 1120,
    beta: 1.0,
    sectorBeta: 1.15,
    baseVolatility: 0.014,
    description: "Private sector bank — simulation reference only.",
  },
  {
    symbol: "KOTAKBANK",
    companyName: "Kotak Mahindra Bank Ltd.",
    exchange: "NSE",
    isin: "INE237A01028",
    sector: "BANKING",
    instrumentType: "EQUITY",
    referencePrice: 1780,
    beta: 0.9,
    sectorBeta: 1.15,
    baseVolatility: 0.013,
    description: "Private sector bank — simulation reference only.",
  },
  {
    symbol: "HINDUNILVR",
    companyName: "Hindustan Unilever Ltd.",
    exchange: "NSE",
    isin: "INE030A01027",
    sector: "FMCG",
    instrumentType: "EQUITY",
    referencePrice: 2380,
    beta: 0.65,
    sectorBeta: 0.85,
    baseVolatility: 0.008,
    description: "FMCG — simulation reference only.",
  },
  {
    symbol: "MARUTI",
    companyName: "Maruti Suzuki India Ltd.",
    exchange: "NSE",
    isin: "INE585B01010",
    sector: "AUTO",
    instrumentType: "EQUITY",
    referencePrice: 12450,
    beta: 1.1,
    sectorBeta: 1.2,
    baseVolatility: 0.013,
    description: "Automobile manufacturer — simulation reference only.",
  },
  {
    symbol: "SUNPHARMA",
    companyName: "Sun Pharmaceutical Industries Ltd.",
    exchange: "NSE",
    isin: "INE044A01036",
    sector: "PHARMA",
    instrumentType: "EQUITY",
    referencePrice: 1680,
    beta: 0.75,
    sectorBeta: 0.9,
    baseVolatility: 0.01,
    description: "Pharmaceuticals — simulation reference only.",
  },
  {
    symbol: "TATAMOTORS",
    companyName: "Tata Motors Ltd.",
    exchange: "NSE",
    isin: "INE155A01022",
    sector: "AUTO",
    instrumentType: "EQUITY",
    referencePrice: 780,
    beta: 1.25,
    sectorBeta: 1.2,
    baseVolatility: 0.016,
    description: "Automobile manufacturer — simulation reference only.",
  },
  {
    symbol: "TATASTEEL",
    companyName: "Tata Steel Ltd.",
    exchange: "NSE",
    isin: "INE081A01020",
    sector: "METALS",
    instrumentType: "EQUITY",
    referencePrice: 145,
    beta: 1.3,
    sectorBeta: 1.25,
    baseVolatility: 0.018,
    description: "Steel producer — simulation reference only.",
  },
  {
    symbol: "WIPRO",
    companyName: "Wipro Ltd.",
    exchange: "NSE",
    isin: "INE075A01022",
    sector: "IT",
    instrumentType: "EQUITY",
    referencePrice: 520,
    beta: 0.8,
    sectorBeta: 1.1,
    baseVolatility: 0.011,
    description: "IT services — simulation reference only.",
  },
  {
    symbol: "BAJFINANCE",
    companyName: "Bajaj Finance Ltd.",
    exchange: "NSE",
    isin: "INE296A01024",
    sector: "FINANCIALS",
    instrumentType: "EQUITY",
    referencePrice: 7200,
    beta: 1.15,
    sectorBeta: 1.1,
    baseVolatility: 0.015,
    description: "NBFC — simulation reference only.",
  },
  {
    symbol: "ADANIENT",
    companyName: "Adani Enterprises Ltd.",
    exchange: "NSE",
    isin: "INE423A01024",
    sector: "INDUSTRIALS",
    instrumentType: "EQUITY",
    referencePrice: 2850,
    beta: 1.35,
    sectorBeta: 1.05,
    baseVolatility: 0.02,
    description: "Conglomerate — simulation reference only.",
  },
  {
    symbol: "ADANIPORTS",
    companyName: "Adani Ports and Special Economic Zone Ltd.",
    exchange: "NSE",
    isin: "INE742F01042",
    sector: "INDUSTRIALS",
    instrumentType: "EQUITY",
    referencePrice: 1420,
    beta: 1.2,
    sectorBeta: 1.05,
    baseVolatility: 0.014,
    description: "Ports & logistics — simulation reference only.",
  },
  {
    symbol: "HCLTECH",
    companyName: "HCL Technologies Ltd.",
    exchange: "NSE",
    isin: "INE860A01027",
    sector: "IT",
    instrumentType: "EQUITY",
    referencePrice: 1680,
    beta: 0.85,
    sectorBeta: 1.1,
    baseVolatility: 0.011,
    description: "IT services — simulation reference only.",
  },
  {
    symbol: "ASIANPAINT",
    companyName: "Asian Paints Ltd.",
    exchange: "NSE",
    isin: "INE021A01026",
    sector: "FMCG",
    instrumentType: "EQUITY",
    referencePrice: 2280,
    beta: 0.7,
    sectorBeta: 0.85,
    baseVolatility: 0.009,
    description: "Paints & coatings — simulation reference only.",
  },
  {
    symbol: "M&M",
    companyName: "Mahindra & Mahindra Ltd.",
    exchange: "NSE",
    isin: "INE101A01026",
    sector: "AUTO",
    instrumentType: "EQUITY",
    referencePrice: 2980,
    beta: 1.15,
    sectorBeta: 1.2,
    baseVolatility: 0.014,
    description: "Automobile & farm equipment — simulation reference only.",
  },
  {
    symbol: "NTPC",
    companyName: "NTPC Ltd.",
    exchange: "NSE",
    isin: "INE733E01010",
    sector: "ENERGY",
    instrumentType: "EQUITY",
    referencePrice: 380,
    beta: 0.85,
    sectorBeta: 1.0,
    baseVolatility: 0.01,
    description: "Power generation — simulation reference only.",
  },
  {
    symbol: "POWERGRID",
    companyName: "Power Grid Corporation of India Ltd.",
    exchange: "NSE",
    isin: "INE752E01010",
    sector: "ENERGY",
    instrumentType: "EQUITY",
    referencePrice: 320,
    beta: 0.75,
    sectorBeta: 1.0,
    baseVolatility: 0.009,
    description: "Power transmission — simulation reference only.",
  },
  {
    symbol: "ULTRACEMCO",
    companyName: "UltraTech Cement Ltd.",
    exchange: "NSE",
    isin: "INE481G01011",
    sector: "INDUSTRIALS",
    instrumentType: "EQUITY",
    referencePrice: 11200,
    beta: 1.0,
    sectorBeta: 1.05,
    baseVolatility: 0.012,
    description: "Cement — simulation reference only.",
  },
  {
    symbol: "TITAN",
    companyName: "Titan Company Ltd.",
    exchange: "NSE",
    isin: "INE280A01028",
    sector: "FMCG",
    instrumentType: "EQUITY",
    referencePrice: 3450,
    beta: 0.9,
    sectorBeta: 0.85,
    baseVolatility: 0.011,
    description: "Jewellery & watches — simulation reference only.",
  },
  {
    symbol: "COALINDIA",
    companyName: "Coal India Ltd.",
    exchange: "NSE",
    isin: "INE522F01014",
    sector: "ENERGY",
    instrumentType: "EQUITY",
    referencePrice: 480,
    beta: 0.9,
    sectorBeta: 1.0,
    baseVolatility: 0.011,
    description: "Coal mining — simulation reference only.",
  },
  {
    symbol: "ONGC",
    companyName: "Oil & Natural Gas Corporation Ltd.",
    exchange: "NSE",
    isin: "INE213A01029",
    sector: "ENERGY",
    instrumentType: "EQUITY",
    referencePrice: 285,
    beta: 1.05,
    sectorBeta: 1.0,
    baseVolatility: 0.013,
    description: "Oil & gas exploration — simulation reference only.",
  },
  {
    symbol: "TECHM",
    companyName: "Tech Mahindra Ltd.",
    exchange: "NSE",
    isin: "INE669C01036",
    sector: "IT",
    instrumentType: "EQUITY",
    referencePrice: 1580,
    beta: 0.85,
    sectorBeta: 1.1,
    baseVolatility: 0.012,
    description: "IT services — simulation reference only.",
  },
];

export const DEMO_STOCKS_LEGACY = [
  {
    symbol: "DEMO1",
    companyName: "Demo Alpha Technologies Ltd.",
    exchange: "NSE" as const,
    isin: "INE000DEMO01",
    sector: "IT",
    instrumentType: "EQUITY" as const,
    referencePrice: 250,
    beta: 1.0,
    sectorBeta: 1.0,
    baseVolatility: 0.015,
    description: "Legacy fictional demo stock — inactive after Phase 16.",
  },
  {
    symbol: "DEMO2",
    companyName: "Demo Beta Financials Ltd.",
    exchange: "NSE" as const,
    isin: "INE000DEMO02",
    sector: "FINANCIALS",
    instrumentType: "EQUITY" as const,
    referencePrice: 180.75,
    beta: 1.0,
    sectorBeta: 1.0,
    baseVolatility: 0.015,
    description: "Legacy fictional demo stock — inactive after Phase 16.",
  },
  {
    symbol: "DEMO3",
    companyName: "Demo Gamma Industries Ltd.",
    exchange: "BSE" as const,
    isin: "INE000DEMO03",
    sector: "INDUSTRIALS",
    instrumentType: "EQUITY" as const,
    referencePrice: 95.25,
    beta: 1.0,
    sectorBeta: 1.0,
    baseVolatility: 0.015,
    description: "Legacy fictional demo stock — inactive after Phase 16.",
  },
];

export const ALL_SECTORS = [
  "IT",
  "BANKING",
  "FINANCIALS",
  "ENERGY",
  "AUTO",
  "PHARMA",
  "FMCG",
  "METALS",
  "TELECOM",
  "INDUSTRIALS",
] as const;
